name: posts_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  equatable: 
  go_router: ^14.6.3
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  dartz: ^0.10.1
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
